"""Small Supabase Postgres and Storage adapter used by the FastAPI app."""

import base64
import os
import uuid
from contextlib import contextmanager
from typing import Iterator

import httpx
import psycopg
from psycopg.rows import dict_row

DATABASE_URL = os.getenv("DATABASE_URL")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
STORAGE_BUCKET = os.getenv("SUPABASE_STORAGE_BUCKET", "catches")


def _require_config() -> None:
    missing = [
        name
        for name, value in {
            "DATABASE_URL": DATABASE_URL,
            "SUPABASE_URL": SUPABASE_URL,
            "SUPABASE_SERVICE_ROLE_KEY": SUPABASE_SERVICE_ROLE_KEY,
        }.items()
        if not value
    ]
    if missing:
        raise RuntimeError(f"Missing Supabase configuration: {', '.join(missing)}")


@contextmanager
def db() -> Iterator[psycopg.Connection]:
    _require_config()
    with psycopg.connect(DATABASE_URL, row_factory=dict_row) as conn:
        yield conn


def init_db() -> None:
    with db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS accounts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                apple_sub TEXT UNIQUE,
                kakao_id TEXT UNIQUE,
                email TEXT,
                nickname TEXT,
                created_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS account_catches (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                account_id BIGINT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
                cloud_name TEXT NOT NULL,
                cloud_type TEXT NOT NULL,
                confidence DOUBLE PRECISION,
                finish TEXT NOT NULL,
                memo TEXT,
                place_name TEXT,
                lat DOUBLE PRECISION,
                lng DOUBLE PRECISION,
                temp_c DOUBLE PRECISION,
                weather_condition TEXT,
                photo_path TEXT,
                captured_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS account_catches_account_id_idx "
            "ON account_catches (account_id, id DESC)"
        )


def save_photo(account_id: int, base64_data: str) -> str:
    _require_config()
    raw = base64_data.split(",", 1)[-1] if base64_data.startswith("data:") else base64_data
    path = f"{account_id}/{uuid.uuid4().hex}.jpg"
    response = httpx.post(
        f"{SUPABASE_URL}/storage/v1/object/{STORAGE_BUCKET}/{path}",
        content=base64.b64decode(raw),
        headers={
            "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
            "apikey": SUPABASE_SERVICE_ROLE_KEY,
            "Content-Type": "image/jpeg",
            "x-upsert": "false",
        },
        timeout=30.0,
    )
    response.raise_for_status()
    return path


def photo_url(path: str | None) -> str | None:
    if not path or not SUPABASE_URL:
        return None
    return f"{SUPABASE_URL}/storage/v1/object/public/{STORAGE_BUCKET}/{path}"